title: Mining Software Engineering Data for Software Reuse
description: Book by Themistoklis Diamantopoulos & Andreas L. Symeonidis
url: "https://thdiaman.github.io"
baseurl: "/mining-software-reuse-book"

styles:
  brand-color: "#268bd2"
  link-text-decoration: none

google_analytics:

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - template
